#!/bin/bash
#SBATCH --job-name=genderize_spark
#SBATCH --output=genderize_spark.out
#SBATCH --error=genderize_spark.err
#SBATCH --time=02:00:00
#SBATCH --mem=64G
#SBATCH --cpus-per-task=2

source /home/emcj/miniconda3/etc/profile.d/conda.sh
conda activate myenv

export JAVA_HOME=$CONDA_PREFIX
export PATH=$JAVA_HOME/bin:$PATH

echo "JAVA_HOME=$JAVA_HOME"
java -version

python /home/emcj/assign_genders_spark.py

