#!/bin/bash
#SBATCH --job-name=betweenness_centrality
#SBATCH --output=betweenness_centrality.out
#SBATCH --error=betweenness_centrality.err
#SBATCH --time=20:00:00
#SBATCH --mem=128G
#SBATCH --cpus-per-task=4
#SBATCH --partition=scavenge

# Activate conda environment
source /home/emcj/miniconda3/etc/profile.d/conda.sh
conda activate myenv

# Run script
python3 /home/emcj/betweenness_centrality.py